# Generated by Django 3.2.12 on 2025-04-07 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userprofile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='recording_url',
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(default='c476571c-09ba-4391-816a-cde1ea6c5287', on_delete=django.db.models.deletion.CASCADE, to='chat.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default='2025-04-08 01:47:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='uploads/'),
        ),
    ]
