# Generated by Django 3.2.12 on 2025-04-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20250408_0212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingRecording',
        ),
    ]
